apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls-secret
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - wisecow.example.com  # Replace with your actual domain
