apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/rohan_regex/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 07 Nov 2024 21:10:11 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://127.0.0.1:32771
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 07 Nov 2024 21:10:11 IST
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/rohan_regex/.minikube/profiles/minikube/client.crt
    client-key: /home/rohan_regex/.minikube/profiles/minikube/client.key