name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD on pushes to the main branch

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rohannigam226 # Set Docker credentials in GitHub Secrets
          password: Rajesh@9926

      - name: Build and push Docker image
        run: |
          docker build -t rohannigam226/wisecow:$GITHUB_SHA .
          docker push Rajesh@9926/wisecow:$GITHUB_SHA

  deploy:
    runs-on: debian-latest
    needs: build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
        
      - name: Set Kubernetes credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-app wisecow-app=rohannigam226/wisecow:$GITHUB_SHA
          kubectl rollout status deployment/wisecow-app
